SELECT
  id,
  LOCK_PLACE_USER_ID,
  CUST_FULL_NAME
FROM BTN_CUST
WHERE lock_place_user_id IS NOT NULL AND exists(SELECT id
                                                FROM wapl_user
                                                WHERE id = LOCK_PLACE_USER_ID);
SELECT *
FROM wapl_user
WHERE id = 38;

[CRITERIA] SELECT
             this_.id                            AS id1_32_5_,
             this_.VERSION                       AS VERSION2_32_5_,
             this_.CREATED_INITIATOR             AS CREATED_INITIATOR3_32_5_,
             this_.CREATED_TS                    AS CREATED_TS4_32_5_,
             this_.CREATED_USER_INFO             AS CREATED_USER_INFO5_32_5_,
             this_.LAST_MODIF_USER_TS            AS LAST_MODIF_USER_TS6_32_5_,
             this_.LAST_MODIF_INITIATOR          AS LAST_MODIF_INITIAT7_32_5_,
             this_.LAST_MODIFIED_TS              AS LAST_MODIFIED_TS8_32_5_,
             this_.LAST_MODIF_USER_INFO          AS LAST_MODIF_USER_IN9_32_5_,
             this_.ACQUISITION_NO                AS ACQUISITION_NO10_32_5_,
             this_.ADVISOR_ID                    AS ADVISOR_ID11_32_5_,
             this_.BONUS_SALES                   AS BONUS_SALES12_32_5_,
             this_.BUSINESS_HOURS                AS BUSINESS_HOURS13_32_5_,
             this_.business_hours_1              AS business_hours_14_32_5_,
             this_.business_hours_2              AS business_hours_15_32_5_,
             this_.business_hours_3              AS business_hours_16_32_5_,
             this_.BUSINESS_HOURS_WINTER         AS BUSINESS_HOURS_WI17_32_5_,
             this_.CARD_NO                       AS CARD_NO18_32_5_,
             this_.CAT_ID                        AS CAT_ID19_32_5_,
             this_.CIP_NOT_MO                    AS CIP_NOT_MO20_32_5_,
             this_.CM_NOTE                       AS CM_NOTE21_32_5_,
             this_.CREDIT_IND                    AS CREDIT_IND22_32_5_,
             this_.CREDIT_LIMIT                  AS CREDIT_LIMIT23_32_5_,
             this_.CREDIT_LIMIT_APPR             AS CREDIT_LIMIT_APPR24_32_5_,
             this_.CREDIT_LIMIT_REQ              AS CREDIT_LIMIT_REQ25_32_5_,
             this_.CREDIT_REQ_BY                 AS CREDIT_REQ_BY26_32_5_,
             this_.CREDIT_SALES                  AS CREDIT_SALES27_32_5_,
             this_.CREDIT_UPDATE_TS              AS CREDIT_UPDATE_TS28_32_5_,
             this_.CUST_BONUS                    AS CUST_BONUS29_32_5_,
             this_.cust_cc                       AS cust_cc30_32_5_,
             this_.cust_cc_store_no              AS cust_cc_store_no31_32_5_,
             this_.CUST_CIP_TYPE                 AS CUST_CIP_TYPE32_32_5_,
             this_.CUST_FULL_NAME                AS CUST_FULL_NAME33_32_5_,
             this_.CUST_GROUP                    AS CUST_GROUP34_32_5_,
             this_.cust_no                       AS cust_no35_32_5_,
             this_.CUST_PAYMENT                  AS CUST_PAYMENT36_32_5_,
             this_.CUST_RECORD_TYPE              AS CUST_RECORD_TYPE37_32_5_,
             this_.CUST_REG_NO                   AS CUST_REG_NO38_32_5_,
             this_.CUST_STATUS                   AS CUST_STATUS39_32_5_,
             this_.DEL_DAYS                      AS DEL_DAYS40_32_5_,
             this_.DEL_DAYS_WINTER               AS DEL_DAYS_WINTER41_32_5_,
             this_.DEL_TYPE                      AS DEL_TYPE42_32_5_,
             this_.DISPOSABLE_LIMIT              AS DISPOSABLE_LIMIT43_32_5_,
             this_.DISTRICT                      AS DISTRICT44_32_5_,
             this_.DIVIDE_NOTE                   AS DIVIDE_NOTE45_32_5_,
             this_.FISC_NO                       AS FISC_NO46_32_5_,
             this_.GPS1                          AS GPS47_32_5_,
             this_.gps1_winter                   AS gps48_32_5_,
             this_.GPS2                          AS GPS49_32_5_,
             this_.gps2_winter                   AS gps50_32_5_,
             this_.HISTORY_PERIOD                AS HISTORY_PERIOD51_32_5_,
             this_.HISTORY_TYPE                  AS HISTORY_TYPE52_32_5_,
             this_.HISTORY_VIEW                  AS HISTORY_VIEW53_32_5_,
             this_.inherit_assortm               AS inherit_assortm102_32_5_,
             this_.inherit_assortm_store_no      AS inherit_assortm_103_32_5_,
             this_.inherit_cip                   AS inherit_cip104_32_5_,
             this_.inherit_cip_store_no          AS inherit_cip_stor105_32_5_,
             this_.inherit_history               AS inherit_history106_32_5_,
             this_.inherit_history_store_no      AS inherit_history_107_32_5_,
             this_.LAST_ASSORTM_MAKER            AS LAST_ASSORTM_MAKE54_32_5_,
             this_.LAST_ASSORTM_UPDATE           AS LAST_ASSORTM_UPDA55_32_5_,
             this_.LAST_MONTH_PROFIT             AS LAST_MONTH_PROFIT56_32_5_,
             this_.LAST_MONTH_SELL               AS LAST_MONTH_SELL57_32_5_,
             this_.LAST_SALE_DATE                AS LAST_SALE_DATE58_32_5_,
             this_.LAST_VISIT_DATE               AS LAST_VISIT_DATE59_32_5_,
             this_.LAST_VISIT_PLACE              AS LAST_VISIT_PLACE60_32_5_,
             this_.LOCK_PLACE                    AS LOCK_PLACE61_32_5_,
             this_.LOCK_PLACE_DATE               AS LOCK_PLACE_DATE62_32_5_,
             this_.lock_place_user_id            AS lock_place_user_108_32_5_,
             this_.NOT_HOLIDAY_DELIVERY          AS NOT_HOLIDAY_DELIV63_32_5_,
             this_.NOT_PROMO                     AS NOT_PROMO64_32_5_,
             this_.note_1                        AS note_65_32_5_,
             this_.note_2                        AS note_66_32_5_,
             this_.note_3                        AS note_67_32_5_,
             this_.note_4                        AS note_68_32_5_,
             this_.note_5                        AS note_69_32_5_,
             this_.NOTE_CALL                     AS NOTE_CALL70_32_5_,
             this_.NOTE_HIDDEN                   AS NOTE_HIDDEN71_32_5_,
             this_.NOTE_PUBLIC                   AS NOTE_PUBLIC72_32_5_,
             this_.NP_MARKUP                     AS NP_MARKUP73_32_5_,
             this_.ORDER_INCOME_TYPE             AS ORDER_INCOME_TYPE74_32_5_,
             this_.ORDER_RESPONS                 AS ORDER_RESPONS75_32_5_,
             this_.order_store                   AS order_store109_32_5_,
             this_.PERIOD_PROFIT                 AS PERIOD_PROFIT76_32_5_,
             this_.PERIOD_SALES                  AS PERIOD_SALES77_32_5_,
             this_.PERIOD_VISIT                  AS PERIOD_VISIT78_32_5_,
             this_.PLACE_ADDRESS                 AS PLACE_ADDRESS79_32_5_,
             this_.PLACE_CUST_REPRESENTATIVE     AS PLACE_CUST_REPRES80_32_5_,
             this_.PLACE_DEL_DATE                AS PLACE_DEL_DATE81_32_5_,
             this_.PLACE_EMAIL                   AS PLACE_EMAIL82_32_5_,
             this_.PLACE_MOBIL_NO                AS PLACE_MOBIL_NO83_32_5_,
             this_.PLACE_NAME                    AS PLACE_NAME84_32_5_,
             this_.place_no                      AS place_no85_32_5_,
             this_.PLACE_PHONE_NO                AS PLACE_PHONE_NO86_32_5_,
             this_.PLACE_POST_CD                 AS PLACE_POST_CD87_32_5_,
             this_.PLACE_REG_DATE                AS PLACE_REG_DATE88_32_5_,
             this_.PLACE_STATUS                  AS PLACE_STATUS89_32_5_,
             this_.PLACE_TOWN                    AS PLACE_TOWN90_32_5_,
             this_.PLACE_TYPE                    AS PLACE_TYPE91_32_5_,
             this_.route_area_id                 AS route_area_id110_32_5_,
             this_.SALES_GROUP                   AS SALES_GROUP92_32_5_,
             this_.SEASON                        AS SEASON93_32_5_,
             this_.SEMAP_GROUP                   AS SEMAP_GROUP94_32_5_,
             this_.SEMAP_NOTE                    AS SEMAP_NOTE95_32_5_,
             this_.store_no                      AS store_no111_32_5_,
             this_.TICKET_LIMIT                  AS TICKET_LIMIT96_32_5_,
             this_.TICKET_STATUS                 AS TICKET_STATUS97_32_5_,
             this_.vip                           AS vip98_32_5_,
             this_.VISIT_DATE                    AS VISIT_DATE99_32_5_,
             this_.VISIT_PLACE                   AS VISIT_PLACE100_32_5_,
             this_.WINTER_MODE                   AS WINTER_MODE101_32_5_,
             this_.route_winter_area_id          AS route_winter_are112_32_5_,
             (SELECT call.cust_full_name
              FROM btn_cust call
              WHERE call.cust_no = this_.inherit_assortm AND call.store_no = this_.inherit_assortm_store_no AND
                    call.cust_record_type = 'Z') AS formula8_5_,
             (SELECT call.cust_full_name
              FROM btn_cust call
              WHERE call.cust_no = this_.inherit_cip AND call.store_no = this_.inherit_cip_store_no AND
                    call.cust_record_type = 'Z') AS formula9_5_,
             (SELECT call.cust_full_name
              FROM btn_cust call
              WHERE call.cust_no = this_.inherit_history AND call.store_no = this_.inherit_history_store_no AND
                    call.cust_record_type = 'Z') AS formula10_5_,
             btnstorev2_.STORE_NO                AS STORE_NO1_94_0_,
             btnstorev2_.DEPOT_IND               AS DEPOT_IND2_94_0_,
             btnstorev2_.DEPOT_STORE_NO          AS DEPOT_STORE_NO3_94_0_,
             btnstorev2_.name                    AS name4_94_0_,
             btnstorev2_.status                  AS status5_94_0_,
             btnstorev2_.STORE_NAME_LIST         AS STORE_NAME_LIST6_94_0_,
             routearea3_.id                      AS id1_89_1_,
             routearea3_.VERSION                 AS VERSION2_89_1_,
             routearea3_.CREATED_INITIATOR       AS CREATED_INITIATOR3_89_1_,
             routearea3_.CREATED_TS              AS CREATED_TS4_89_1_,
             routearea3_.CREATED_USER_INFO       AS CREATED_USER_INFO5_89_1_,
             routearea3_.LAST_MODIF_USER_TS      AS LAST_MODIF_USER_TS6_89_1_,
             routearea3_.LAST_MODIF_INITIATOR    AS LAST_MODIF_INITIAT7_89_1_,
             routearea3_.LAST_MODIFIED_TS        AS LAST_MODIFIED_TS8_89_1_,
             routearea3_.LAST_MODIF_USER_INFO    AS LAST_MODIF_USER_IN9_89_1_,
             routearea3_.ROUTE_AREA_DESC         AS ROUTE_AREA_DESC10_89_1_,
             routearea3_.ROUTE_AREA_STATUS       AS ROUTE_AREA_STATUS11_89_1_,
             routearea3_.ROUTE_NO                AS ROUTE_NO12_89_1_,
             routearea3_.store_no                AS store_no13_89_1_,
             btnstorev4_.STORE_NO                AS STORE_NO1_94_2_,
             btnstorev4_.DEPOT_IND               AS DEPOT_IND2_94_2_,
             btnstorev4_.DEPOT_STORE_NO          AS DEPOT_STORE_NO3_94_2_,
             btnstorev4_.name                    AS name4_94_2_,
             btnstorev4_.status                  AS status5_94_2_,
             btnstorev4_.STORE_NAME_LIST         AS STORE_NAME_LIST6_94_2_,
             btnstorev5_.STORE_NO                AS STORE_NO1_94_3_,
             btnstorev5_.DEPOT_IND               AS DEPOT_IND2_94_3_,
             btnstorev5_.DEPOT_STORE_NO          AS DEPOT_STORE_NO3_94_3_,
             btnstorev5_.name                    AS name4_94_3_,
             btnstorev5_.status                  AS status5_94_3_,
             btnstorev5_.STORE_NAME_LIST         AS STORE_NAME_LIST6_94_3_,
             routearea6_.id                      AS id1_89_4_,
             routearea6_.VERSION                 AS VERSION2_89_4_,
             routearea6_.CREATED_INITIATOR       AS CREATED_INITIATOR3_89_4_,
             routearea6_.CREATED_TS              AS CREATED_TS4_89_4_,
             routearea6_.CREATED_USER_INFO       AS CREATED_USER_INFO5_89_4_,
             routearea6_.LAST_MODIF_USER_TS      AS LAST_MODIF_USER_TS6_89_4_,
             routearea6_.LAST_MODIF_INITIATOR    AS LAST_MODIF_INITIAT7_89_4_,
             routearea6_.LAST_MODIFIED_TS        AS LAST_MODIFIED_TS8_89_4_,
             routearea6_.LAST_MODIF_USER_INFO    AS LAST_MODIF_USER_IN9_89_4_,
             routearea6_.ROUTE_AREA_DESC         AS ROUTE_AREA_DESC10_89_4_,
             routearea6_.ROUTE_AREA_STATUS       AS ROUTE_AREA_STATUS11_89_4_,
             routearea6_.ROUTE_NO                AS ROUTE_NO12_89_4_,
             routearea6_.store_no                AS store_no13_89_4_
           FROM BTN_CUST this_ LEFT OUTER JOIN BTN_STORE_V btnstorev2_ ON this_.order_store = btnstorev2_.STORE_NO
             LEFT OUTER JOIN BTN_ROUTE_AREA routearea3_ ON this_.route_area_id = routearea3_.id
             LEFT OUTER JOIN BTN_STORE_V btnstorev4_ ON routearea3_.store_no = btnstorev4_.STORE_NO
             LEFT OUTER JOIN BTN_STORE_V btnstorev5_ ON this_.store_no = btnstorev5_.STORE_NO
             LEFT OUTER JOIN BTN_ROUTE_AREA routearea6_ ON this_.route_winter_area_id = routearea6_.id
           WHERE this_.id = ?