
SELECT PROFILE, LIMIT FROM DBA_PROFILES WHERE RESOURCE_NAME = 'IDLE_TIME';

SELECT PROFILE FROM DBA_USERS WHERE USERNAME = 'BTN_APL';

update dba_profiles set limit = 1 where RESOURCE_NAME = 'IDLE_TIME' and profile = 'DEFAULT';