SELECT *
FROM BTN_DOC_LINE dl
WHERE dl.LINE_STATUS = 'X' AND dl.DOC_TYPE = 'OBP' AND exists(SELECT d.id
                                                              FROM btn_doc d
                                                              WHERE d.id = dl.BTN_DOC_ID);

SELECT
  d.id,
  count(dl.id) as cnt
FROM btn_doc d left join btn_doc_line dl on d.ID = dl.BTN_DOC_ID
GROUP BY d.ID
HAVING count(dl.ID) > 10
ORDER BY cnt desc;

UPDATE BTN_DOC_LINE
SET LINE_STATUS = 'X'
WHERE BTN_DOC_ID = 800022852;

SELECT *
FROM btn_doc
WHERE DOC_NO = '800022852';

SELECT *
FROM btn_doc
WHERE id = '2238130';

select max(id) from BTN_DOC;

select * from btn_doc order by doc_no desc;

SELECT
  this_.id                                                          AS id1_50_10_,
  this_.VERSION                                                     AS VERSION2_50_10_,
  this_.CREATED_INITIATOR                                           AS CREATED_INITIATOR3_50_10_,
  this_.CREATED_TS                                                  AS CREATED_TS4_50_10_,
  this_.CREATED_USER_INFO                                           AS CREATED_USER_INFO5_50_10_,
  this_.LAST_MODIF_USER_TS                                          AS LAST_MODIF_USER_TS6_50_10_,
  this_.LAST_MODIF_INITIATOR                                        AS LAST_MODIF_INITIAT7_50_10_,
  this_.LAST_MODIFIED_TS                                            AS LAST_MODIFIED_TS8_50_10_,
  this_.LAST_MODIF_USER_INFO                                        AS LAST_MODIF_USER_IN9_50_10_,
  this_.ADVISOR_ID                                                  AS ADVISOR_ID10_50_10_,
  this_.BTN_ROUTE_ID                                                AS BTN_ROUTE_ID11_50_10_,
  this_.BUY_PRICE_1                                                 AS BUY_PRICE_12_50_10_,
  this_.BUY_PRICE_2                                                 AS BUY_PRICE_13_50_10_,
  this_.CANCEL_TYPE                                                 AS CANCEL_TYPE14_50_10_,
  this_.CANCEL_USER_ID                                              AS CANCEL_USER_ID15_50_10_,
  this_.COD_COMMENT                                                 AS COD_COMMENT16_50_10_,
  this_.COD_DELIVERY                                                AS COD_DELIVERY17_50_10_,
  this_.COD_INVOICE                                                 AS COD_INVOICE18_50_10_,
  this_.COD_PICKING                                                 AS COD_PICKING19_50_10_,
  this_.COD_SELL_PRICE                                              AS COD_SELL_PRICE20_50_10_,
  this_.COUNT_LINE                                                  AS COUNT_LINE21_50_10_,
  this_.CURRENCY                                                    AS CURRENCY22_50_10_,
  this_.CUST_CIP_TYPE                                               AS CUST_CIP_TYPE23_50_10_,
  this_.CUST_FULL_NAME                                              AS CUST_FULL_NAME24_50_10_,
  this_.CUST_NO                                                     AS CUST_NO25_50_10_,
  this_.CUST_STORE_NO                                               AS CUST_STORE_NO88_50_10_,
  this_.DDC_CUST_NO                                                 AS DDC_CUST_NO26_50_10_,
  this_.DDC_STORE_NO                                                AS DDC_STORE_NO27_50_10_,
  this_.BTN_DEL_TYPE_ID                                             AS BTN_DEL_TYPE_ID89_50_10_,
  this_.DIVIDE_DOC                                                  AS DIVIDE_DOC28_50_10_,
  this_.DIVIDE_NOTE                                                 AS DIVIDE_NOTE29_50_10_,
  this_.DOC_CLOSE                                                   AS DOC_CLOSE30_50_10_,
  this_.DOC_CLOSE_USER_ID                                           AS DOC_CLOSE_USER_ID31_50_10_,
  this_.DOC_COD_EXPORT                                              AS DOC_COD_EXPORT32_50_10_,
  this_.DOC_CONTACT                                                 AS DOC_CONTACT33_50_10_,
  this_.DOC_DATE                                                    AS DOC_DATE34_50_10_,
  this_.DOC_DATE_CREATE                                             AS DOC_DATE_CREATE35_50_10_,
  this_.DOC_DATE_DEL                                                AS DOC_DATE_DEL36_50_10_,
  this_.DOC_DDC                                                     AS DOC_DDC37_50_10_,
  this_.DOC_NO                                                      AS DOC_NO38_50_10_,
  this_.DOC_NOTE                                                    AS DOC_NOTE39_50_10_,
  this_.DOC_NOTE_ADMIN                                              AS DOC_NOTE_ADMIN40_50_10_,
  this_.DOC_PAYMENT                                                 AS DOC_PAYMENT41_50_10_,
  this_.DOC_STATUS                                                  AS DOC_STATUS42_50_10_,
  this_.DOC_TYPE                                                    AS DOC_TYPE43_50_10_,
  this_.DOC_TYPE_PACK                                               AS DOC_TYPE_PACK44_50_10_,
  this_.EXT_DEL_TYPE                                                AS EXT_DEL_TYPE45_50_10_,
  this_.EXT_STORE_NO                                                AS EXT_STORE_NO46_50_10_,
  this_.EXTERNAL_DOC_ID                                             AS EXTERNAL_DOC_ID47_50_10_,
  this_.EXTERNAL_DOC_NO                                             AS EXTERNAL_DOC_NO48_50_10_,
  this_.FLAG_DATE                                                   AS FLAG_DATE49_50_10_,
  this_.FLAG_STATUS                                                 AS FLAG_STATUS50_50_10_,
  this_.flag_user_id                                                AS flag_user_id90_50_10_,
  this_.IND_INVOICE                                                 AS IND_INVOICE51_50_10_,
  this_.INVOICE_NO                                                  AS INVOICE_NO52_50_10_,
  this_.INVOICE_STORE_NO                                            AS INVOICE_STORE_NO53_50_10_,
  this_.NORMAL_SELL_PRICE                                           AS NORMAL_SELL_PRICE54_50_10_,
  this_.NOTE_HIDDEN                                                 AS NOTE_HIDDEN55_50_10_,
  this_.NOTE_PUBLIC                                                 AS NOTE_PUBLIC56_50_10_,
  this_.ORDER_INCOME_TYPE                                           AS ORDER_INCOME_TYPE57_50_10_,
  this_.ORDER_PROCESSOR                                             AS ORDER_PROCESSOR58_50_10_,
  this_.ORDER_SELL_PRICE                                            AS ORDER_SELL_PRICE59_50_10_,
  this_.ORDER_SOURCE                                                AS ORDER_SOURCE60_50_10_,
  this_.OWN_DOC_NO                                                  AS OWN_DOC_NO61_50_10_,
  this_.PL_UPDATE_STATUS                                            AS PL_UPDATE_STATUS62_50_10_,
  this_.PLACE_ADDRESS                                               AS PLACE_ADDRESS63_50_10_,
  this_.PLACE_CUST_REPRESENTATIVE                                   AS PLACE_CUST_REPRES64_50_10_,
  this_.PLACE_MOBIL_NO                                              AS PLACE_MOBIL_NO65_50_10_,
  this_.PLACE_NAME                                                  AS PLACE_NAME66_50_10_,
  this_.PLACE_NO                                                    AS PLACE_NO67_50_10_,
  this_.PLACE_PHONE_NO                                              AS PLACE_PHONE_NO68_50_10_,
  this_.PLACE_POST_CD                                               AS PLACE_POST_CD69_50_10_,
  this_.PLACE_TOWN                                                  AS PLACE_TOWN70_50_10_,
  this_.preord_dt_from                                              AS preord_dt_from71_50_10_,
  this_.preord_dt_to                                                AS preord_dt_to72_50_10_,
  this_.preord_ord2cust                                             AS preord_ord73_50_10_,
  this_.preord_ord2supl                                             AS preord_ord74_50_10_,
  this_.PREORD_ORD_PLACE                                            AS PREORD_ORD_PLACE75_50_10_,
  this_.PREORD_PERIOD_TYPE                                          AS PREORD_PERIOD_TYP76_50_10_,
  this_.PREORD_PERIOD_VAL                                           AS PREORD_PERIOD_VAL77_50_10_,
  this_.PREORD_TYPE                                                 AS PREORD_TYPE78_50_10_,
  this_.SELL_PRICE                                                  AS SELL_PRICE79_50_10_,
  this_.SELL_PRICE_VAT                                              AS SELL_PRICE_VAT80_50_10_,
  this_.STORE_NO                                                    AS STORE_NO91_50_10_,
  this_.STORE_SELL_PRICE                                            AS STORE_SELL_PRICE81_50_10_,
  this_.STORE_TYPE                                                  AS STORE_TYPE82_50_10_,
  this_.SUM_VOLUME                                                  AS SUM_VOLUME83_50_10_,
  this_.SUM_WEIGHT                                                  AS SUM_WEIGHT84_50_10_,
  this_.TILL_NO                                                     AS TILL_NO85_50_10_,
  this_.VALIDATION_RESULT                                           AS VALIDATION_RESULT86_50_10_,
  this_.WASTE_TAX_AMNT                                              AS WASTE_TAX_AMNT87_50_10_,
  (SELECT COUNT(1)
   FROM BTN_DOC_LINE dl
   WHERE dl.BTN_DOC_ID = this_.ID AND dl.DOC_DATE = this_.DOC_DATE) AS formula13_10_,
  btnstorev2_.STORE_NO                                              AS STORE_NO1_94_0_,
  btnstorev2_.DEPOT_IND                                             AS DEPOT_IND2_94_0_,
  btnstorev2_.DEPOT_STORE_NO                                        AS DEPOT_STORE_NO3_94_0_,
  btnstorev2_.name                                                  AS name4_94_0_,
  btnstorev2_.status                                                AS status5_94_0_,
  btnstorev2_.STORE_NAME_LIST                                       AS STORE_NAME_LIST6_94_0_,
  deliveryty3_.id                                                   AS id1_45_1_,
  deliveryty3_.VERSION                                              AS VERSION2_45_1_,
  deliveryty3_.CREATED_INITIATOR                                    AS CREATED_INITIATOR3_45_1_,
  deliveryty3_.CREATED_TS                                           AS CREATED_TS4_45_1_,
  deliveryty3_.CREATED_USER_INFO                                    AS CREATED_USER_INFO5_45_1_,
  deliveryty3_.LAST_MODIF_USER_TS                                   AS LAST_MODIF_USER_TS6_45_1_,
  deliveryty3_.LAST_MODIF_INITIATOR                                 AS LAST_MODIF_INITIAT7_45_1_,
  deliveryty3_.LAST_MODIFIED_TS                                     AS LAST_MODIFIED_TS8_45_1_,
  deliveryty3_.LAST_MODIF_USER_INFO                                 AS LAST_MODIF_USER_IN9_45_1_,
  deliveryty3_.CALC_TYPE                                            AS CALC_TYPE10_45_1_,
  deliveryty3_.CFA                                                  AS CFA11_45_1_,
  deliveryty3_.COD_DEL_TYPE                                         AS COD_DEL_TYPE12_45_1_,
  deliveryty3_.COD_DEL_TYPE_2                                       AS COD_DEL_TYPE_13_45_1_,
  deliveryty3_.COD_PRICE_TYPE                                       AS COD_PRICE_TYPE14_45_1_,
  deliveryty3_.COD_PRICE_TYPE_PROMO                                 AS COD_PRICE_TYPE_PR15_45_1_,
  deliveryty3_.COD_SETUP_NOTE                                       AS COD_SETUP_NOTE16_45_1_,
  deliveryty3_.COD_STORE                                            AS COD_STORE17_45_1_,
  deliveryty3_.DEL_TYPE                                             AS DEL_TYPE18_45_1_,
  deliveryty3_.DEL_TYPE_GRP                                         AS DEL_TYPE_GRP19_45_1_,
  deliveryty3_.DEL_TYPE_GRP_CFA                                     AS DEL_TYPE_GRP_CFA20_45_1_,
  deliveryty3_.DESCRIPTION                                          AS DESCRIPTION21_45_1_,
  deliveryty3_.MM_TYPE                                              AS MM_TYPE22_45_1_,
  deliveryty3_.MO_DEL_TYPE                                          AS MO_DEL_TYPE23_45_1_,
  deliveryty3_.ORD                                                  AS ORD24_45_1_,
  deliveryty3_.PRICE_MATRIX                                         AS PRICE_MATRIX25_45_1_,
  deliveryty3_.STATUS                                               AS STATUS26_45_1_,
  deliveryty3_.WEIGHT_MARGE                                         AS WEIGHT_MARGE27_45_1_,
  user4_.id                                                         AS id1_149_2_,
  user4_.VERSION                                                    AS VERSION2_149_2_,
  user4_.CREATED_INITIATOR                                          AS CREATED_INITIATOR3_149_2_,
  user4_.CREATED_TS                                                 AS CREATED_TS4_149_2_,
  user4_.CREATED_USER_INFO                                          AS CREATED_USER_INFO5_149_2_,
  user4_.LAST_MODIF_USER_TS                                         AS LAST_MODIF_USER_TS6_149_2_,
  user4_.LAST_MODIF_INITIATOR                                       AS LAST_MODIF_INITIAT7_149_2_,
  user4_.LAST_MODIFIED_TS                                           AS LAST_MODIFIED_TS8_149_2_,
  user4_.LAST_MODIF_USER_INFO                                       AS LAST_MODIF_USER_IN9_149_2_,
  user4_.DB_VALID                                                   AS DB_VALID10_149_2_,
  user4_.db_valid_store_no                                          AS db_valid_store_no18_149_2_,
  user4_.locale_id                                                  AS locale_id19_149_2_,
  user4_.LOGIN_AD                                                   AS LOGIN_AD11_149_2_,
  user4_.LOGIN_DB                                                   AS LOGIN_DB12_149_2_,
  user4_.name                                                       AS name13_149_2_,
  user4_.region_id                                                  AS region_id20_149_2_,
  user4_.status                                                     AS status14_149_2_,
  user4_.surname                                                    AS surname15_149_2_,
  user4_.VALID_FROM                                                 AS VALID_FROM16_149_2_,
  user4_.VALID_TO                                                   AS VALID_TO17_149_2_,
  store5_.STORE_NO                                                  AS STORE_NO1_148_3_,
  store5_.DEPOT_IND                                                 AS DEPOT_IND2_148_3_,
  store5_.DEPOT_STORE_NO                                            AS DEPOT_STORE_NO3_148_3_,
  store5_.name                                                      AS name4_148_3_,
  store5_.status                                                    AS status5_148_3_,
  store5_.town                                                      AS town6_148_3_,
  locale6_.id                                                       AS id1_137_4_,
  locale6_.VERSION                                                  AS VERSION2_137_4_,
  locale6_.CREATED_INITIATOR                                        AS CREATED_INITIATOR3_137_4_,
  locale6_.CREATED_TS                                               AS CREATED_TS4_137_4_,
  locale6_.CREATED_USER_INFO                                        AS CREATED_USER_INFO5_137_4_,
  locale6_.LAST_MODIF_USER_TS                                       AS LAST_MODIF_USER_TS6_137_4_,
  locale6_.LAST_MODIF_INITIATOR                                     AS LAST_MODIF_INITIAT7_137_4_,
  locale6_.LAST_MODIFIED_TS                                         AS LAST_MODIFIED_TS8_137_4_,
  locale6_.LAST_MODIF_USER_INFO                                     AS LAST_MODIF_USER_IN9_137_4_,
  locale6_.name                                                     AS name10_137_4_,
  locale6_.status                                                   AS status11_137_4_,
  region7_.id                                                       AS id1_141_5_,
  region7_.VERSION                                                  AS VERSION2_141_5_,
  region7_.CREATED_INITIATOR                                        AS CREATED_INITIATOR3_141_5_,
  region7_.CREATED_TS                                               AS CREATED_TS4_141_5_,
  region7_.CREATED_USER_INFO                                        AS CREATED_USER_INFO5_141_5_,
  region7_.LAST_MODIF_USER_TS                                       AS LAST_MODIF_USER_TS6_141_5_,
  region7_.LAST_MODIF_INITIATOR                                     AS LAST_MODIF_INITIAT7_141_5_,
  region7_.LAST_MODIFIED_TS                                         AS LAST_MODIFIED_TS8_141_5_,
  region7_.LAST_MODIF_USER_INFO                                     AS LAST_MODIF_USER_IN9_141_5_,
  region7_.lvl                                                      AS lvl10_141_5_,
  region7_.name                                                     AS name11_141_5_,
  region7_.note                                                     AS note12_141_5_,
  region7_.status                                                   AS status13_141_5_,
  userdetail8_.id                                                   AS id1_150_6_,
  userdetail8_.VERSION                                              AS VERSION2_150_6_,
  userdetail8_.CREATED_INITIATOR                                    AS CREATED_INITIATOR3_150_6_,
  userdetail8_.CREATED_TS                                           AS CREATED_TS4_150_6_,
  userdetail8_.CREATED_USER_INFO                                    AS CREATED_USER_INFO5_150_6_,
  userdetail8_.LAST_MODIF_USER_TS                                   AS LAST_MODIF_USER_TS6_150_6_,
  userdetail8_.LAST_MODIF_INITIATOR                                 AS LAST_MODIF_INITIAT7_150_6_,
  userdetail8_.LAST_MODIFIED_TS                                     AS LAST_MODIFIED_TS8_150_6_,
  userdetail8_.LAST_MODIF_USER_INFO                                 AS LAST_MODIF_USER_IN9_150_6_,
  userdetail8_.ADVISOR_ID                                           AS ADVISOR_ID10_150_6_,
  userdetail8_.CARD                                                 AS CARD11_150_6_,
  userdetail8_.CARD_DATE                                            AS CARD_DATE12_150_6_,
  userdetail8_.CARD_LOAD                                            AS CARD_LOAD13_150_6_,
  userdetail8_.DRIVER_LIC                                           AS DRIVER_LIC14_150_6_,
  userdetail8_.email_1                                              AS email_15_150_6_,
  userdetail8_.email_2                                              AS email_16_150_6_,
  userdetail8_.impersonation_region_id                              AS impersonation_reg36_150_6_,
  userdetail8_.MOBIL_NO                                             AS MOBIL_NO17_150_6_,
  userdetail8_.MPL                                                  AS MPL18_150_6_,
  userdetail8_.note_1                                               AS note_19_150_6_,
  userdetail8_.note_2                                               AS note_20_150_6_,
  userdetail8_.note_3                                               AS note_21_150_6_,
  userdetail8_.note_4                                               AS note_22_150_6_,
  userdetail8_.note_5                                               AS note_23_150_6_,
  userdetail8_.PHONE_NO                                             AS PHONE_NO24_150_6_,
  userdetail8_.STORE_NO                                             AS STORE_NO25_150_6_,
  userdetail8_.supervisor_user_id                                   AS supervisor_user_i37_150_6_,
  userdetail8_.training_1                                           AS training_26_150_6_,
  userdetail8_.training_2                                           AS training_27_150_6_,
  userdetail8_.training_3                                           AS training_28_150_6_,
  userdetail8_.TRAINING_BT                                          AS TRAINING_BT29_150_6_,
  userdetail8_.TRAINING_CFM                                         AS TRAINING_CFM30_150_6_,
  userdetail8_.TRAINING_COD                                         AS TRAINING_COD31_150_6_,
  userdetail8_.TRAINING_MO                                          AS TRAINING_MO32_150_6_,
  userdetail8_.user_id                                              AS user_id38_150_6_,
  userdetail8_.USER_CODE                                            AS USER_CODE33_150_6_,
  userdetail8_.USER_FUNCTION                                        AS USER_FUNCTION34_150_6_,
  userdetail8_.USER_NOTE                                            AS USER_NOTE35_150_6_,
  region9_.id                                                       AS id1_141_7_,
  region9_.VERSION                                                  AS VERSION2_141_7_,
  region9_.CREATED_INITIATOR                                        AS CREATED_INITIATOR3_141_7_,
  region9_.CREATED_TS                                               AS CREATED_TS4_141_7_,
  region9_.CREATED_USER_INFO                                        AS CREATED_USER_INFO5_141_7_,
  region9_.LAST_MODIF_USER_TS                                       AS LAST_MODIF_USER_TS6_141_7_,
  region9_.LAST_MODIF_INITIATOR                                     AS LAST_MODIF_INITIAT7_141_7_,
  region9_.LAST_MODIFIED_TS                                         AS LAST_MODIFIED_TS8_141_7_,
  region9_.LAST_MODIF_USER_INFO                                     AS LAST_MODIF_USER_IN9_141_7_,
  region9_.lvl                                                      AS lvl10_141_7_,
  region9_.name                                                     AS name11_141_7_,
  region9_.note                                                     AS note12_141_7_,
  region9_.status                                                   AS status13_141_7_,
  user10_.id                                                        AS id1_149_8_,
  user10_.VERSION                                                   AS VERSION2_149_8_,
  user10_.CREATED_INITIATOR                                         AS CREATED_INITIATOR3_149_8_,
  user10_.CREATED_TS                                                AS CREATED_TS4_149_8_,
  user10_.CREATED_USER_INFO                                         AS CREATED_USER_INFO5_149_8_,
  user10_.LAST_MODIF_USER_TS                                        AS LAST_MODIF_USER_TS6_149_8_,
  user10_.LAST_MODIF_INITIATOR                                      AS LAST_MODIF_INITIAT7_149_8_,
  user10_.LAST_MODIFIED_TS                                          AS LAST_MODIFIED_TS8_149_8_,
  user10_.LAST_MODIF_USER_INFO                                      AS LAST_MODIF_USER_IN9_149_8_,
  user10_.DB_VALID                                                  AS DB_VALID10_149_8_,
  user10_.db_valid_store_no                                         AS db_valid_store_no18_149_8_,
  user10_.locale_id                                                 AS locale_id19_149_8_,
  user10_.LOGIN_AD                                                  AS LOGIN_AD11_149_8_,
  user10_.LOGIN_DB                                                  AS LOGIN_DB12_149_8_,
  user10_.name                                                      AS name13_149_8_,
  user10_.region_id                                                 AS region_id20_149_8_,
  user10_.status                                                    AS status14_149_8_,
  user10_.surname                                                   AS surname15_149_8_,
  user10_.VALID_FROM                                                AS VALID_FROM16_149_8_,
  user10_.VALID_TO                                                  AS VALID_TO17_149_8_,
  btnstorev11_.STORE_NO                                             AS STORE_NO1_94_9_,
  btnstorev11_.DEPOT_IND                                            AS DEPOT_IND2_94_9_,
  btnstorev11_.DEPOT_STORE_NO                                       AS DEPOT_STORE_NO3_94_9_,
  btnstorev11_.name                                                 AS name4_94_9_,
  btnstorev11_.status                                               AS status5_94_9_,
  btnstorev11_.STORE_NAME_LIST                                      AS STORE_NAME_LIST6_94_9_
FROM BTN_DOC this_ LEFT OUTER JOIN BTN_STORE_V btnstorev2_ ON this_.CUST_STORE_NO = btnstorev2_.STORE_NO
  LEFT OUTER JOIN BTN_DEL_TYPE deliveryty3_ ON this_.BTN_DEL_TYPE_ID = deliveryty3_.id
  LEFT OUTER JOIN WAPL_USER user4_ ON this_.flag_user_id = user4_.id
  LEFT OUTER JOIN WAPL_STORE store5_ ON user4_.db_valid_store_no = store5_.STORE_NO
  LEFT OUTER JOIN WAPL_LOCALE locale6_ ON user4_.locale_id = locale6_.id
  LEFT OUTER JOIN WAPL_REGION region7_ ON user4_.region_id = region7_.id
  LEFT OUTER JOIN WAPL_USER_DETAIL userdetail8_ ON user4_.id = userdetail8_.user_id
  LEFT OUTER JOIN WAPL_REGION region9_ ON userdetail8_.impersonation_region_id = region9_.id
  LEFT OUTER JOIN WAPL_USER user10_ ON userdetail8_.supervisor_user_id = user10_.id
  INNER JOIN BTN_STORE_V btnstorev11_ ON this_.STORE_NO = btnstorev11_.STORE_NO
WHERE this_.PREORD_TYPE = 'J' AND this_.DOC_STATUS = 'O';