CREATE USER BTN4_JMSADMIN IDENTIFIED BY BTN4_JMSADMIN DEFAULT TABLESPACE users;
GRANT CONNECT TO BTN4_JMSADMIN;
GRANT CREATE TYPE TO BTN4_JMSADMIN;
GRANT aq_administrator_role TO BTN4_JMSADMIN;
GRANT CREATE any TRIGGER to BTN4_JMSADMIN;
GRANT CREATE PROCEDURE TO BTN4_JMSADMIN;
GRANT EXECUTE ON SYS.DBMS_AQ to BTN4_JMSADMIN;

GRANT SELECT ON BT_OWNER.BT_CUST TO BTN4_JMSADMIN;
GRANT SELECT ON BT_OWNER.BT_CUST_Z TO BTN4_JMSADMIN;
GRANT SELECT ON BT_OWNER.BT_CUST_P TO BTN4_JMSADMIN;
GRANT SELECT ON MD_CUST_OWNER.CUST TO BTN4_JMSADMIN;
GRANT SELECT ON MD_CUST_OWNER.CUST_ADDRESS_PLACE TO BTN4_JMSADMIN;
GRANT SELECT ON MD_CUST_OWNER.CUST_NOM TO BTN4_JMSADMIN;
GRANT SELECT ON MD_CUST_OWNER.CUST_ACQ TO BTN4_JMSADMIN;

ALTER USER BTN4_JMSADMIN QUOTA UNLIMITED ON users;

CREATE USER BTN4_JMSUSER identified by BTN4_JMSUSER;
GRANT CREATE SESSION to BTN4_JMSUSER;
GRANT aq_user_role TO BTN4_JMSUSER;

connect BTN4_JMSADMIN/BTN4_JMSADMIN

EXECUTE DBMS_AQADM.CREATE_QUEUE_TABLE (queue_table => 'BTN4_JMSADMIN.jms_btn_cust_search_qtbl', queue_payload_type => 'SYS.AQ$_JMS_TEXT_MESSAGE');
EXECUTE DBMS_AQADM.CREATE_QUEUE (queue_name => 'BTN4_JMSADMIN.jms_cust_search_queue', queue_table => 'BTN4_JMSADMIN.jms_btn_cust_search_qtbl');
EXECUTE DBMS_AQADM.START_QUEUE (Queue_name => 'BTN4_JMSADMIN.jms_cust_search_queue');
EXECUTE DBMS_AQADM.grant_queue_privilege (privilege => 'ALL', queue_name => 'BTN4_JMSADMIN.jms_cust_search_queue', grantee => 'BTN4_JMSUSER', grant_option => FALSE);
